/**
 * PayslipUpload Component
 *
 * Allows admin/ops to upload a PDF payslip for a worker.
 * When uploaded, the system-generated payslip is replaced — workers
 * will see the uploaded PDF instead of the auto-generated breakdown.
 */

import React, { useState, useRef } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  TextField,
  Stack,
  Alert,
  LinearProgress,
  Paper,
  Chip,
} from '@mui/material';
import {
  UploadFile,
  PictureAsPdf,
  CheckCircle,
  Close,
  CloudUpload,
  InfoOutlined,
} from '@mui/icons-material';

interface PayslipUploadProps {
  workerId: string;
  workerName?: string;
  payPeriodType?: 'WEEKLY' | 'MONTHLY';
  onSuccess?: (payslipId: string, periodLabel: string) => void;
}

const toISODate = (d: Date) => d.toISOString().slice(0, 10);

const todayISO = () => toISODate(new Date());

/** Compute period boundaries from a reference date */
function computePeriod(dateStr: string, type: 'WEEKLY' | 'MONTHLY') {
  const [y, m, d] = dateStr.split('-').map(Number);
  const ref = new Date(y, m - 1, d);
  if (type === 'WEEKLY') {
    const day = ref.getDay();
    const diff = day === 0 ? -6 : 1 - day;
    const start = new Date(ref);
    start.setDate(ref.getDate() + diff);
    const end = new Date(start);
    end.setDate(start.getDate() + 6);
    return {
      start,
      end,
      label: `Week ${start.toLocaleDateString('en-GB', { day: '2-digit', month: 'short' })} – ${end.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}`,
    };
  } else {
    const start = new Date(y, m - 1, 1);
    const end = new Date(y, m, 0);
    return {
      start,
      end,
      label: start.toLocaleString('en-GB', { month: 'long', year: 'numeric' }),
    };
  }
}

export const PayslipUpload: React.FC<PayslipUploadProps> = ({
  workerId,
  workerName,
  payPeriodType = 'MONTHLY',
  onSuccess,
}) => {
  const [payPeriodDate, setPayPeriodDate] = useState<string>(todayISO);
  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [success, setSuccess] = useState<{ payslipId: string; label: string } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [dragOver, setDragOver] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const period = payPeriodDate ? computePeriod(payPeriodDate, payPeriodType) : null;

  const handleFileSelect = (selected: File | null) => {
    if (!selected) return;
    if (selected.type !== 'application/pdf') {
      setError('Only PDF files are accepted.');
      return;
    }
    if (selected.size > 10 * 1024 * 1024) {
      setError('File must be under 10 MB.');
      return;
    }
    setFile(selected);
    setError(null);
    setSuccess(null);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    const dropped = e.dataTransfer.files[0];
    handleFileSelect(dropped ?? null);
  };

  const handleUpload = async () => {
    if (!file || !payPeriodDate) return;

    setUploading(true);
    setError(null);

    const formData = new FormData();
    formData.append('file', file);
    formData.append('workerId', workerId);
    formData.append('payPeriodDate', payPeriodDate);

    try {
      const token = localStorage.getItem('token') ?? sessionStorage.getItem('token');
      const res = await fetch('/api/v1/payslips/upload', {
        method: 'POST',
        headers: token ? { Authorization: `Bearer ${token}` } : {},
        body: formData,
      });

      const json = await res.json();
      if (!res.ok) throw new Error(json.message ?? 'Upload failed');

      const label = json.data.periodLabel ?? period?.label ?? payPeriodDate;
      setSuccess({ payslipId: json.data.payslipId, label });
      setFile(null);
      onSuccess?.(json.data.payslipId, label);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Upload failed');
    } finally {
      setUploading(false);
    }
  };

  return (
    <Box sx={{ maxWidth: 640, mx: 'auto', p: 2 }}>
      <Stack spacing={3}>
        <Box>
          <Typography variant="h6" fontWeight={700}>Upload Payslip PDF</Typography>
          <Typography variant="body2" color="text.secondary">
            Upload a payslip PDF generated by your payroll software. Workers will see this
            instead of the system-generated breakdown.
          </Typography>
          {workerName && (
            <Chip label={workerName} size="small" sx={{ mt: 1 }} />
          )}
        </Box>

        {/* Info banner */}
        <Alert severity="info" icon={<InfoOutlined fontSize="small" />}>
          <Typography variant="caption">
            <strong>Upload replaces generated payslip.</strong> If a system-generated payslip
            already exists for the chosen {payPeriodType === 'WEEKLY' ? 'week' : 'month'}, it
            will be replaced by your uploaded PDF. Workers will only see the uploaded version.
          </Typography>
        </Alert>

        {/* Pay period selector */}
        <Card variant="outlined">
          <CardContent>
            <Typography variant="subtitle2" fontWeight={600} gutterBottom>
              {payPeriodType === 'WEEKLY' ? 'Select any date within the week' : 'Select any date within the month'}
            </Typography>
            <TextField
              type="date"
              value={payPeriodDate}
              onChange={(e) => setPayPeriodDate(e.target.value)}
              size="small"
              fullWidth
              inputProps={{ max: todayISO() }}
            />
            {period && (
              <Box sx={{ mt: 1.5, p: 1.5, bgcolor: 'primary.50', borderRadius: 1 }}>
                <Typography variant="caption" color="primary.main" fontWeight={600}>
                  {payPeriodType === 'WEEKLY' ? '📅 Week:' : '📅 Month:'}&nbsp;
                  {period.label}
                </Typography>
                {payPeriodType === 'WEEKLY' && (
                  <Typography variant="caption" color="text.secondary" display="block">
                    {toISODate(period.start)} – {toISODate(period.end)}
                  </Typography>
                )}
              </Box>
            )}
          </CardContent>
        </Card>

        {/* File drop zone */}
        <Card variant="outlined">
          <CardContent>
            <Typography variant="subtitle2" fontWeight={600} gutterBottom>Payslip PDF</Typography>
            <Paper
              variant="outlined"
              onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
              onDragLeave={() => setDragOver(false)}
              onDrop={handleDrop}
              onClick={() => inputRef.current?.click()}
              sx={{
                p: 4,
                textAlign: 'center',
                cursor: 'pointer',
                borderStyle: 'dashed',
                borderColor: dragOver ? 'primary.main' : file ? 'success.main' : 'divider',
                bgcolor: dragOver ? 'primary.50' : file ? 'success.50' : 'background.default',
                transition: 'all 0.15s',
                '&:hover': { borderColor: 'primary.main', bgcolor: 'primary.50' },
              }}
            >
              <input
                ref={inputRef}
                type="file"
                accept="application/pdf"
                hidden
                onChange={(e) => handleFileSelect(e.target.files?.[0] ?? null)}
              />
              {file ? (
                <Stack alignItems="center" spacing={1}>
                  <PictureAsPdf sx={{ fontSize: 40, color: 'error.main' }} />
                  <Typography variant="body2" fontWeight={600}>{file.name}</Typography>
                  <Typography variant="caption" color="text.secondary">
                    {(file.size / 1024).toFixed(1)} KB
                  </Typography>
                  <Button
                    size="small"
                    color="inherit"
                    startIcon={<Close />}
                    onClick={(e) => { e.stopPropagation(); setFile(null); }}
                  >
                    Remove
                  </Button>
                </Stack>
              ) : (
                <Stack alignItems="center" spacing={1}>
                  <CloudUpload sx={{ fontSize: 40, color: 'text.disabled' }} />
                  <Typography variant="body2" fontWeight={500}>
                    Drop PDF here or click to browse
                  </Typography>
                  <Typography variant="caption" color="text.secondary">
                    PDF only · max 10 MB
                  </Typography>
                </Stack>
              )}
            </Paper>
          </CardContent>
        </Card>

        {/* Progress */}
        {uploading && <LinearProgress />}

        {/* Success */}
        {success && (
          <Alert severity="success" icon={<CheckCircle />}>
            <Typography variant="body2">
              <strong>Payslip uploaded successfully</strong> for {success.label}.
              Workers will now see this PDF in the app.
            </Typography>
          </Alert>
        )}

        {/* Error */}
        {error && <Alert severity="error">{error}</Alert>}

        {/* Upload button */}
        <Button
          variant="contained"
          size="large"
          startIcon={<UploadFile />}
          onClick={handleUpload}
          disabled={!file || !payPeriodMonth || uploading}
          fullWidth
        >
          {uploading ? 'Uploading…' : 'Upload Payslip'}
        </Button>
      </Stack>
    </Box>
  );
};
